Models/Admin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreProject.Models
{
    public class Admin
    {
        [Key]
        public int AdminID { get; set; }
        [Column(TypeName = "varchar(10)")]
        public string Kullanici { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string Sifre { get; set; }
    }
}

Models/Birim.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
namespace CoreProject.Models
{
    public class Birim
    {
        [Key]
        public int BirimID { get; set; }
        public string BirimAd { get; set; }

        public IList<Personel> Personels { get; set; }
    }
}

Models/Context.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace CoreProject.Models
{
    public class Context : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=LAPTOP-EFPS8KL8; database= CoreProject; integrated security= true");
        }

        public DbSet<Birim> Birims { get; set; }
        public DbSet<Personel> Personels { get; set; }
        public DbSet<Admin> Admins { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CoreProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Personel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace CoreProject.Models
{
    public class Personel
    {
        [Key]

        public int PersonelID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sehir { get; set; }
        public int BirimID { get; set; }
        public Birim Birim { get; set; }
    }
}

Controllers/BirimController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreProject.Models;
namespace CoreProject.Controllers
{
    public class BirimController : Controller
    {

        Context db = new Context();
        public IActionResult Index()
        {
            List<Birim> birimler = db.Birims.ToList();

            return View(birimler);
        }

        public IActionResult YeniBirim()
        {
            return View();
        }

        [HttpPost]
        public IActionResult YeniBirim(Birim d)
        {
            db.Birims.Add(d);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult BirimSil(int id)
        {
            var dep = db.Birims.Find(id);

            db.Birims.Remove(dep);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult BirimGetir(int ID)
        {
            var dep = db.Birims.Find(ID);

            return View(dep);
        }

        [HttpPost]
        public IActionResult BirimGüncelle(Birim dep)
        {
            var birim = db.Birims.Find(dep.BirimID);

            birim.BirimAd = dep.BirimAd;


            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult BirimDetay(int ID)
        {
            List<Personel> personeller = db.Personels.Where(x => x.BirimID == ID).ToList();
            var birimAdı = db.Birims.Where(x => x.BirimID == ID).Select(y => y.BirimAd).FirstOrDefault();

            ViewBag.BirimAd = birimAdı;
            return View(personeller);
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreProject.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace CoreProject.Controllers
{
    public class LoginController : Controller
    {
        Context db = new Context();
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Giris(Admin a)
        {
            var bilgiler = db.Admins.FirstOrDefault(x => x.Kullanici == a.Kullanici && x.Sifre == a.Sifre);

            if (bilgiler != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, a.Kullanici)
                };

                var userIdentity = new ClaimsIdentity(claims, "Login");

                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

                await HttpContext.SignInAsync(principal);

                return RedirectToAction("PersonelGetir", "Personel");
            }

            return View();
        }

    }
}

Controllers/PersonelController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace CoreProject.Controllers
{
    public class PersonelController : Controller
    {
        Context db = new Context();

        [Authorize]
        public IActionResult Index()
        {
            List<Personel> personeller = db.Personels.Include(x => x.Birim).ToList();
            return View(personeller);
        }

        public IActionResult YeniPersonel()
        {
            List<SelectListItem> degerler = (from x in db.Birims.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.BirimAd,
                                                 Value = x.BirimID.ToString()
                                             }
                                             ).ToList();

            ViewBag.dgr = degerler;

            return View();
        }

        [HttpPost]

        public IActionResult YeniPersonel(Personel p)
        {
            
            // Filter by matching each instance id of Birims collection in database
            // with incoming input's id and show the first result
            var per = db.Birims.Where(x => x.BirimID == p.Birim.BirimID).FirstOrDefault();
            // Assign incoming parameter's Birim property to retrieved data from database
            p.Birim = per;
            db.Personels.Add(p);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult PersonelSil (int ID)
        {
            var personel = db.Personels.Find(ID);
            db.Personels.Remove(personel);
            db.SaveChanges();

            return RedirectToAction("Index");
        }



        public IActionResult PersonelGetir(int ID)
        {
            List<SelectListItem> birimler = (from x in db.Birims.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.BirimAd,
                                                 Value = x.BirimID.ToString()
                                             }
                                             ).ToList();

            var personel = db.Personels.Find(ID);

            ViewBag.birims = birimler;
            return View(personel);
        }

        public IActionResult PersonelGüncelle(Personel personel)
        {
            var findPersonel = db.Personels.Find(personel.PersonelID);
            findPersonel.Ad = personel.Ad;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Views/Birim/BirimDetay.cshtml
@model List<Personel>

@{
    ViewData["Title"] = "BirimDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<h4>@ViewBag.BirimAd</h4>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Ad
            </th>
            <th>
                Soyad
            </th>
            <th>
                Sehir
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>

                <td>
                    @x.PersonelID
                </td>
                <td>
                    @x.Ad
                </td>
                <td>
                    @x.Soyad
                </td>
                <td>
                    @x.Sehir
                </td>
                <!--<th>-->
                @*@x.Birim.BirimAd*@
                <!--</th>-->
            </tr>

        }
    </tbody>
</table>

Views/Birim/BirimGetir.cshtml
@model CoreProject.Models.Birim;

@{
    ViewData["Title"] = "BirimGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />

@using (

     Html.BeginForm("BirimGüncelle", "Birim", FormMethod.Post)
 )
{
    <b>Birim ID</b>
    @Html.TextBoxFor(x => x.BirimID, new { @class = "form-control" })
    <b>Birim Ad</b>
    @Html.TextBoxFor(x => x.BirimAd, new { @class = "form-control" })
    <button class="btn btn-info">Güncelle</button>
}

Views/Birim/Index.cshtml
@using CoreProject.Models;
@model List<Birim>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Departman</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Detaylar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.BirimID</td>
                <td>@x.BirimAd</td>
                <td>@Html.ActionLink("Sil", "BirimSil", new { ID = x.BirimID }, new { @class = "btn btn-danger" })</td>
                <td>@Html.ActionLink("Güncelle", "BirimGetir", new { ID = x.BirimID }, new { @class = "btn btn-info" })</td>
                <td>
                    @Html.ActionLink("Detaylar", "BirimDetay", "Birim", new { ID = x.BirimID}, new {@class = "btn btn-primary"} )
                </td>
            </tr>
        }
    </tbody>
</table>

<a href="/birim/yenibirim" class="btn btn-info">Yeni Birim</a>

Views/Birim/YeniBirim.cshtml
@model CoreProject.Models.Birim;
@{
    ViewData["Title"] = "YeniBirim";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.BirimAd)
    @Html.TextBoxFor(x => x.BirimAd, new { @class = "form-control" })
    <button type="submit" class="btn btn-info">Ekle</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Login/Giris.cshtml
@{
    Layout = null;
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>Blend Login Form Flat Responsive Widget Template :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Blend  Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/web/css/style.css" rel="stylesheet" />

    <link href="~/web/css/font-awesome.css" rel="stylesheet">  @*Font-Awesome-Icons-CSS*@ 
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Vollkorn+SC:400,600,700,900&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Acme" rel="stylesheet">
    <!-- //web font -->
</head>
<body>
    <!-- main -->
    <div class="main">
        <h1>Blend  Login Form</h1>
        <div class="main-w3lsrow">
            <!-- login form -->
            <div class="login-form login-form-left">
                <div class="agile-row">
                    <h2>Login Here</h2>
                    <div class="login-agileits-top">
                        <form action="#" method="post">
                            <p>User Name </p>
                            <input type="text" class="name" name="Kullanici" required="" />
                            <p>Password</p>
                            <input type="password" class="password" name="Sifre" required="" />
                            <label class="anim">
                                <input type="checkbox" class="checkbox">
                                <span> Remember me ?</span>
                            </label>
                            <input type="submit" value="Login">
                        </form>
                    </div>
                    <div class="login-agileits-bottom">
                        <h6><a href="#">Forgot password?</a></h6>
                    </div>
                    <div class="login-agileits-bottom1">
                        <h3>(or)</h3>

                    </div>
                    <div class="social_icons agileinfo">
                        <ul class="top-links">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
        <!-- copyright -->
        <div class="copyright">
            <p> © 2018 Blend  Login Form. All rights reserved | Design by <a href="http://w3layouts.com/" target="_blank">W3layouts</a></p>
        </div>
        <!-- //copyright -->
    </div>
    <!-- //main -->
</body>
</html>

Views/Personel/Index.cshtml
@using CoreProject.Models;
@model List<Personel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Ad
            </th>
            <th>
                Soyad
            </th>
            <th>
                Sehir
            </th>
            <th>
                Departman
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>
                    @x.PersonelID
                </td>
                <td>
                    @x.Ad
                </td>
                <td>
                    @x.Soyad
                </td>
                <td>
                    @x.Sehir
                </td>
                <td>
                    @x.Birim.BirimAd
                </td>
                <td>
                    @Html.ActionLink("Sil", "PersonelSil", "Personel", new {ID = x.PersonelID }, new {@class = "btn btn-danger" })  
                </td>
                <td>
                    @Html.ActionLink("Güncelle", "PersonelGetir", "Personel", new { ID = x.PersonelID }, new { @class = "btn btn-info" })
                </td>
                <td>
                    @*<a class="btn btn-primary" href="/personel/personelgetir">Detaylar</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>

<a href="/personel/yenipersonel" class="btn btn-success">Yeni Personel</a>

Views/Personel/PersonelGetir.cshtml
@model CoreProject.Models.Personel
@{
    ViewData["Title"] = "PersonelGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

@using (Html.BeginForm("PersonelGüncelle", "Personel", FormMethod.Post))
{
    <br />
    @Html.LabelFor(x => x.PersonelID)
    @Html.TextBoxFor(x => x.PersonelID, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Ad)
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Soyad)
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Sehir)
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <br />
    @Html.DropDownListFor(x => x.Birim.BirimID, (List<SelectListItem>)ViewBag.birims, new { @class = "form-control" })
    <br />
    <button type="submit">Güncelle</button>
}

Views/Personel/PersonelGüncelle.cshtml
@model CoreProject.Models.Personel;
@{
    ViewData["Title"] = "PersonelGüncelle";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

@using (Html.BeginForm("PersonelGüncelle", "Personel", FormMethod.Post))
{
    <br />
    @Html.LabelFor(x => x.Ad)
    @Html.TextBoxFor(x => x.Ad)
    <br />
    @Html.LabelFor(x => x.Soyad)
    @Html.TextBoxFor(x => x.Soyad)
    <br />
    @Html.LabelFor(x => x.Sehir)
    @Html.TextBoxFor(x => x.Sehir)
    <br />
    @Html.LabelFor(x=> x.Birim.BirimAd)
    @*@Html.TextBoxFor()*@
}

Views/Personel/YeniPersonel.cshtml
@model CoreProject.Models.Personel;

@{
    ViewData["Title"] = "YeniPersonel";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

@using (Html.BeginForm("YeniPersonel", "Personel", FormMethod.Post))
{
    <br />
    @Html.LabelFor(x => x.Ad)
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Soyad)
    @Html.TextBoxFor(x => x.Soyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Sehir)
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Birim.BirimAd)
    // Selected model property will be bound to the selected value from dropdown list
    // The source of options will come from ViewBag.dgr and converted into a list form of SelectListItem type
    @Html.DropDownListFor(x => x.Birim.BirimID, (List<SelectListItem>)ViewBag.dgr, new {@class= "form-control" })
    <br />
    <button class="btn btn-success">Ekle</button>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CoreProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_TestLayout.cshtml
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
        <h3 class="w3-bar-item">Menu</h3>
        <a href="/birim/index" class="w3-bar-item w3-button">Birimler</a>
        <a href="/personel/index" class="w3-bar-item w3-button">Personel</a>
        <a href="/hakkımızda" class="w3-bar-item w3-button">Hakkımızda</a>
        <a href="/login/giris" class="w3-bar-item w3-button">Giriş</a>
        <a href="#" class="w3-bar-item w3-button">Çıkış</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:25%">

        <div class="w3-container w3-teal">
            <h1>My Page</h1>
        </div>


        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>